runtime: nodejs20
build_env_variables:
  GOOGLE_NODE_RUN_SCRIPTS: ''
env_variables:
  PROD: '1'
entrypoint: 'node server.js --port 8080'
instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 15m
